name: Mirror to Public Repo

on:
  push:
    branches: [main]   # Déclenche sur la branche main

# Permissions minimales pour lire le dépôt privé
permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # historique complet pour push --mirror

      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to public mirror
        env:
          MIRROR_URL: https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/${{ secrets.MIRROR_REPO }}.git
        run: |
          # Ajoute le remote du miroir (idempotent)
          if git remote | grep -q '^mirror$'; then
            git remote set-url mirror "$MIRROR_URL"
          else
            git remote add mirror "$MIRROR_URL"
          fi

          # Synchronise tout (branches + tags) et purge ce qui a été supprimé
          git push --mirror mirror

