name: Mirror to Public Repo
on:

  push:
    branches: [main]   # Trigger on pushes to main

# Minimal permissions to read private repo
permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history for push --mirror

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to public mirror
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
          MIRROR_REPO:  ${{ secrets.MIRROR_REPO }}
        run: |
          set -euo pipefail

          # sanitize secrets in case of accidental newlines/spaces
          TOKEN="$(printf %s "$MIRROR_TOKEN" | tr -d '\r\n')"
          REPO="$(printf %s "$MIRROR_REPO"  | tr -d '\r\n ')"
          REPO="${REPO%.git}"

          REMOTE_URL="https://x-access-token:${TOKEN}@github.com/${REPO}.git"
          echo "Remote = https://x-access-token:***@github.com/${REPO}.git"

          # idempotent remote add
          git remote remove mirror || true
          git remote add mirror "$REMOTE_URL"

          # mirror push (branches + tags + refs)
          git push --mirror mirror
