name: Mirror to Public Repo

on:
  push:
    branches: [ main ]  # déclenche sur la branche main

permissions:
  contents: read        # lecture du dépôt privé par l'action

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # historique complet pour --mirror

      - name: Configure Git
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to public mirror
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
          MIRROR_REPO:  ${{ secrets.MIRROR_REPO }}   # ex: housse99-hash/edusafira-demo-public
        run: |
          set -euo pipefail

          # élimine tout retour à la ligne / espace parasite venu des secrets
          TOKEN="$(printf %s "$MIRROR_TOKEN" | tr -d '\r\n')"
          DEST="$(printf %s "$MIRROR_REPO"  | tr -d '\r\n ')"
          DEST="${DEST%.git}"   # tolère si vous avez mis .git par erreur

          REMOTE_URL="https://x-access-token:${TOKEN}@github.com/${DEST}.git"
          echo "Pushing to github.com/${DEST}.git"

          # idempotent : on (re)crée le remote 'mirror'
          git remote remove mirror || true
          git remote add mirror "$REMOTE_URL"

          # push miroir (toutes branches / tags / refs)
          git push --mirror mirror
