name: Mirror to Public Repo (SSH)

on:
  push:
    branches: [ main ]         # déclenche au push sur main
  workflow_dispatch:            # lancement manuel possible

permissions:
  contents: read                # permissions minimales pour Actions

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add GitHub host keys
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printf '%s\n' "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Push to public mirror
        env:
          DEST: ${{ secrets.MIRROR_REPO }}   # ex: housse99-hash/edusafira-demo-public
        run: |
          set -euo pipefail
          DEST="$(printf %s "$DEST" | tr -d '\r\n ')"
          DEST="${DEST%.git}"
          REMOTE_URL="git@github.com:${DEST}.git"

          git remote remove mirror || true
          git remote add mirror "$REMOTE_URL"
          git push --mirror mirror
        git remote add mirror git@github.com:housse99-hash/edusafira-demo-public.git
          git push --mirror mirror
