name: Mirror to Public Repo (SSH)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add GitHub host keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Disable workflows for public mirror
        run: |
          mkdir -p .github/workflows
          for f in .github/workflows/*.yml; do
            if [ -f "$f" ]; then
              echo "# DISABLED FOR PUBLIC MIRROR" | cat - "$f" > temp && mv temp "$f"
            fi
          done

      - name: Push to public mirror
        run: |
          git remote remove mirror || true
          git remote add mirror "git@github.com:${{ secrets.MIRROR_REPO }}.git"
          git push --mirror mirror
