name: Mirror to Public Repo

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # host-key: option non supportée ici, on gère juste après

      - name: Add known_hosts (safe)
        if: secrets.SSH_KNOWN_HOSTS != ''
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Add known_hosts (fallback)
        if: secrets.SSH_KNOWN_HOSTS == ''
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Push to public mirror (SSH)
        run: |
          set -euo pipefail
          git remote remove mirror || true
          # ⚠️ Remplace par VOTRE repo public en SSH :
          git remote add mirror git@github.com:housse99-hash/edusafira-demo-public.git
          git push --mirror mirror
