name: Uptime & SSL Monitor

on:
  schedule:
    # Tous les matins à 07:00 UTC (modifie si besoin)
    - cron: "0 7 * * *"
  workflow_dispatch: {}

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run monitor
        run: |
          bash .github/monitor/monitor.sh | tee monitor_out.txt
        shell: bash

      - name: Upload log (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: monitor-log
          path: monitor_out.txt

      # Si ça échoue, on crée automatiquement une Issue avec le log
      - name: Create Issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('monitor_out.txt', 'utf8');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Uptime/SSL alert – ${new Date().toISOString()}`,
              body
            });
